build:
	@docker build -t ruger-bot .

run:
	@docker run -dp 3000:3000 --name ruger-bot ruger-bot

stop:
	@docker stop ruger-bot

clear:
	@docker rm ruger-bot

up: build run

down: stop clear

all: down up