build:
	@docker build -t ruger-bot .

run:
	@docker run -dp 3000:3000 --name ruger-bot ruger-bot

stop:
	@docker stop ruger-bot

clear:
	@docker rm ruger-bot

start: build run

wipe: stop clear

all: wipe start